"""add product is_active

Revision ID: b75f85e64e75
Revises: 1aa939ad4df2
Create Date: 2026-08-24 13:41:03.777560

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b75f85e64e75'
down_revision = '1aa939ad4df2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # server_default กันพัง ถ้า migration นี้รันบนตารางที่มีข้อมูลอยู่แล้วในอนาคต
    # (ตอนนี้ตารางว่าง แต่ NOT NULL ไม่มี default จะ fail ทันทีที่มีข้อมูลจริง)
    op.add_column(
        'products',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###
