"""add product images and low stock alert debounce

Revision ID: be870d0e0389
Revises: b75f85e64e75
Create Date: 2026-08-24 15:02:47.339950

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'be870d0e0389'
down_revision = 'b75f85e64e75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('branch_skus', sa.Column('low_stock_alert_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch_skus', 'low_stock_alert_sent_at')
    op.drop_table('product_images')
    # ### end Alembic commands ###
